# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a10926c1cf1da47a175e834ca2e276f54f6cf11e46205fad95453056d46069f49d5c437293deb5d0e0b1d22da38087138b41027f55c0e79fba7fbfae2d5b886b

test:
  secret_key_base: d741d4de4cb6ae3b2bbd001c2c1d31f34784084868f14814982f01fb5e96182b52b67372e2cb17ba726a0762de83ff44d6bece7d294e83f8714e6a94e5078424

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
